// <auto-generated />
namespace MissingPet.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Removed_Unnecessary_Foreign_Key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed_Unnecessary_Foreign_Key));
        
        string IMigrationMetadata.Id
        {
            get { return "201911281641038_Removed_Unnecessary_Foreign_Key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
